<?php
/**
 * @copyright Copyright (c) sbdevblog (http://www.sbdevblog.com)
 */

use SbDevBlog\Config\Block\CheckAvailability;
use Magento\Framework\Escaper;

/**
 * @var CheckAvailability $block
 * @var Escaper $escaper
 */
?>

<div id="showbox">
    <div>
        <input id="postcode" type="text" title="<?= $escaper->escapeHtml(__('Enter Postcode')) ?>"
               placeholder="<?= $escaper->escapeHtml(__('Enter Postcode')) ?>">
    </div>
    <div style="margin-top: 10px">
        <button id="checkAvail" class="button action primary" type="button">
            <span><?= $escaper->escapeHtml(__("Check Availability")) ?></span>
        </button>
    </div>
</div>
<script type="text/x-magento-init">
{
    "#checkAvail": {
        "SbDevBlog_Config/js/view/skustatus": {
            "skuConfig": <?= /** @noEscape */
    $block->getCheckAvailability() ?>,
            "productSku": "<?= $escaper->escapeHtml($block->getCurrentSku()) ?>"
        }
    }
}





</script>
